appname = mcp-gateway
httpport = 9000
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true

[dev]
oauth.secret = your-secret-key-dev

[prod]
oauth.secret = ${OAUTH_SECRET||your-secret-key}
